/**
 * Which civil time a country keeps — the data behind
 * src/utils/timezone.ts → timeZoneForPlace. IANA zone names, which every
 * runtime's Intl understands.
 */

/** Countries that keep one civil time (mainland), by ISO 3166-1 alpha-2. */
export const COUNTRY_ZONE: Record<string, string> = {
  AD: 'Europe/Andorra',
  AE: 'Asia/Dubai',
  AL: 'Europe/Tirane',
  AM: 'Asia/Yerevan',
  AT: 'Europe/Vienna',
  AZ: 'Asia/Baku',
  BA: 'Europe/Sarajevo',
  BD: 'Asia/Dhaka',
  BE: 'Europe/Brussels',
  BG: 'Europe/Sofia',
  BO: 'America/La_Paz',
  BY: 'Europe/Minsk',
  CH: 'Europe/Zurich',
  CN: 'Asia/Shanghai',
  CO: 'America/Bogota',
  CR: 'America/Costa_Rica',
  CU: 'America/Havana',
  CY: 'Asia/Nicosia',
  CZ: 'Europe/Prague',
  DE: 'Europe/Berlin',
  DK: 'Europe/Copenhagen',
  DO: 'America/Santo_Domingo',
  DZ: 'Africa/Algiers',
  EE: 'Europe/Tallinn',
  EG: 'Africa/Cairo',
  ES: 'Europe/Madrid',
  ET: 'Africa/Addis_Ababa',
  FI: 'Europe/Helsinki',
  FR: 'Europe/Paris',
  GB: 'Europe/London',
  GE: 'Asia/Tbilisi',
  GH: 'Africa/Accra',
  GR: 'Europe/Athens',
  GT: 'America/Guatemala',
  HK: 'Asia/Hong_Kong',
  HN: 'America/Tegucigalpa',
  HR: 'Europe/Zagreb',
  HU: 'Europe/Budapest',
  IE: 'Europe/Dublin',
  IL: 'Asia/Jerusalem',
  IN: 'Asia/Kolkata',
  IQ: 'Asia/Baghdad',
  IR: 'Asia/Tehran',
  IS: 'Atlantic/Reykjavik',
  IT: 'Europe/Rome',
  JM: 'America/Jamaica',
  JO: 'Asia/Amman',
  JP: 'Asia/Tokyo',
  KE: 'Africa/Nairobi',
  KR: 'Asia/Seoul',
  LB: 'Asia/Beirut',
  LI: 'Europe/Vaduz',
  LK: 'Asia/Colombo',
  LT: 'Europe/Vilnius',
  LU: 'Europe/Luxembourg',
  LV: 'Europe/Riga',
  MA: 'Africa/Casablanca',
  MC: 'Europe/Monaco',
  MD: 'Europe/Chisinau',
  ME: 'Europe/Podgorica',
  MK: 'Europe/Skopje',
  MT: 'Europe/Malta',
  MY: 'Asia/Kuala_Lumpur',
  NG: 'Africa/Lagos',
  NI: 'America/Managua',
  NL: 'Europe/Amsterdam',
  NO: 'Europe/Oslo',
  NP: 'Asia/Kathmandu',
  NZ: 'Pacific/Auckland',
  PA: 'America/Panama',
  PE: 'America/Lima',
  PH: 'Asia/Manila',
  PK: 'Asia/Karachi',
  PL: 'Europe/Warsaw',
  PR: 'America/Puerto_Rico',
  PT: 'Europe/Lisbon',
  PY: 'America/Asuncion',
  QA: 'Asia/Qatar',
  RO: 'Europe/Bucharest',
  RS: 'Europe/Belgrade',
  RW: 'Africa/Kigali',
  SA: 'Asia/Riyadh',
  SE: 'Europe/Stockholm',
  SG: 'Asia/Singapore',
  SI: 'Europe/Ljubljana',
  SK: 'Europe/Bratislava',
  SM: 'Europe/San_Marino',
  SN: 'Africa/Dakar',
  SV: 'America/El_Salvador',
  TH: 'Asia/Bangkok',
  TN: 'Africa/Tunis',
  TR: 'Europe/Istanbul',
  TW: 'Asia/Taipei',
  TZ: 'Africa/Dar_es_Salaam',
  UA: 'Europe/Kyiv',
  UG: 'Africa/Kampala',
  UY: 'America/Montevideo',
  VA: 'Europe/Vatican',
  VE: 'America/Caracas',
  VN: 'Asia/Ho_Chi_Minh',
  ZA: 'Africa/Johannesburg',
  ZW: 'Africa/Harare',
};

/**
 * Large countries spanning several zones: the zone by longitude, west to east.
 * Approximate at the borders by design — a county line is not a meridian — but
 * right for the cities people actually hold events in.
 */
export const MULTI_ZONE_BANDS: Record<string, Array<[number, string]>> = {
  // [longitude the zone starts at (east of), zone]
  // Alaska and Hawaii share longitudes — told apart by latitude below.
  US: [
    [-125, 'America/Los_Angeles'],
    [-114, 'America/Denver'],
    [-101, 'America/Chicago'],
    [-86, 'America/New_York'],
  ],
  CA: [
    [-141, 'America/Vancouver'],
    [-120, 'America/Edmonton'],
    [-102, 'America/Winnipeg'],
    [-90, 'America/Toronto'],
    [-67, 'America/Halifax'],
    [-60, 'America/St_Johns'],
  ],
  MX: [
    [-118, 'America/Tijuana'],
    [-109, 'America/Mazatlan'],
    [-102, 'America/Mexico_City'],
    [-88, 'America/Cancun'],
  ],
  BR: [
    [-74, 'America/Rio_Branco'],
    [-67, 'America/Manaus'],
    [-52, 'America/Sao_Paulo'],
  ],
  AU: [
    [112, 'Australia/Perth'],
    [129, 'Australia/Adelaide'],
    [141, 'Australia/Sydney'],
  ],
  AR: [[-74, 'America/Argentina/Buenos_Aires']],
  CL: [
    [-110, 'Pacific/Easter'],
    [-76, 'America/Santiago'],
  ],
  ID: [
    [95, 'Asia/Jakarta'],
    [115, 'Asia/Makassar'],
    [126, 'Asia/Jayapura'],
  ],
  RU: [
    [19, 'Europe/Kaliningrad'],
    [27, 'Europe/Moscow'],
    [50, 'Europe/Samara'],
    [60, 'Asia/Yekaterinburg'],
    [73, 'Asia/Omsk'],
    [82, 'Asia/Novosibirsk'],
    [97, 'Asia/Irkutsk'],
    [113, 'Asia/Yakutsk'],
    [130, 'Asia/Vladivostok'],
    [147, 'Asia/Magadan'],
    [160, 'Asia/Kamchatka'],
  ],
  KZ: [
    [46, 'Asia/Aqtobe'],
    [61, 'Asia/Almaty'],
  ],
};
